// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-psh2Eq3UwjQwWBZ2FpZw4Gl-b8yKwk',
    appId: '1:340155939358:web:94df5431e026ca2bed8c0f',
    messagingSenderId: '340155939358',
    projectId: 'e-commerce-3f460',
    authDomain: 'e-commerce-3f460.firebaseapp.com',
    storageBucket: 'e-commerce-3f460.firebasestorage.app',
    measurementId: 'G-R8JGNYD3FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuAZAfFXY8B2xNm7cvnWKGvDvtWAd5oFM',
    appId: '1:340155939358:android:f56084a438e08e2ded8c0f',
    messagingSenderId: '340155939358',
    projectId: 'e-commerce-3f460',
    storageBucket: 'e-commerce-3f460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMC5FVaisFpVGYhYSsOD8RVFyABvmVM0',
    appId: '1:340155939358:ios:059385457e03ecdeed8c0f',
    messagingSenderId: '340155939358',
    projectId: 'e-commerce-3f460',
    storageBucket: 'e-commerce-3f460.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzMC5FVaisFpVGYhYSsOD8RVFyABvmVM0',
    appId: '1:340155939358:ios:059385457e03ecdeed8c0f',
    messagingSenderId: '340155939358',
    projectId: 'e-commerce-3f460',
    storageBucket: 'e-commerce-3f460.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW-psh2Eq3UwjQwWBZ2FpZw4Gl-b8yKwk',
    appId: '1:340155939358:web:4289fc0c6227c407ed8c0f',
    messagingSenderId: '340155939358',
    projectId: 'e-commerce-3f460',
    authDomain: 'e-commerce-3f460.firebaseapp.com',
    storageBucket: 'e-commerce-3f460.firebasestorage.app',
    measurementId: 'G-CMGX52XSKM',
  );
}
